Console.Write.Line("Client: Das ist die erste Zeile")
Console.Write.Line("Client: Das ist die zweite Zeile")
Console.Write.Line("Client: Das ist die dritte Zeile")
Console.Write.Line("Client: Das ist die vierte Zeile")
Console.Write.Line("Client: Das ist die fünfte Zeile")
Console.Write.Line("Github: Das ist die vierte Zeile")
Console.Write.Line("Github: Das ist die fünfte Zeile")